services:
  traefik:
    image: traefik:v3.5
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.lenc.acme.email=ssl@avii.ovh"
      - "--certificatesresolvers.lenc.acme.storage=/letsencrypt/acme.json" # Path inside container volume
      - "--certificatesresolvers.lenc.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.websecure.http.tls.certresolver=lenc"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--experimental.plugins.traefik-oidc-auth.modulename=github.com/sevensolutions/traefik-oidc-auth"
      - "--experimental.plugins.traefik-oidc-auth.version=v0.16.0"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /letsencrypt:/letsencrypt
    networks:
      - proxy
    restart: unless-stopped
    labels:
      # Service Labels
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.avii.ovh`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # Middleware for OIDC authentication
      #- "traefik.http.routers.traefik.middlewares=oidc-auth"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.secret=MLFs4TT99kOOq8h3UAVRtYoCTDYXiRcZ" # Please change this secret for your setup
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.url=id.avii.ovh"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.clientid=yourclientidhere"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.clientsecret=yourclientsecrethere"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.scopes=openid email profile"

networks:
  proxy: