services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    restart: unless-stopped
    ports:
      - 1411:1411
    volumes:
      - "/data:/app/data"
    environment:
      APP_URL=${POCKETID_APP_URL}
      TRUST_PROXY=${TRUST_PROXY}
      MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      PUID=1000
      PGID=1000
    labels:
      # Service Labels
      - "traefik.enable=true"
      - "traefik.http.routers.pocketid.rule=Host(`${FQDN_TRAEFIK}`)"
      - "traefik.http.routers.pocketid.entrypoints=websecure"
      - "traefik.http.services.pocketid.loadbalancer.server.port=1411"
      # Middleware for OIDC authentication
      #- "traefik.http.routers.traefik.middlewares=oidc-auth"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.secret=${OIDC_SECRET}" # Please change this secret for your setup
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.url=${OIDC_URL}"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.clientid=${OIDC_CLIENTID}"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.clientsecret=${OIDC_CLIENTSECRET}"
      - "traefik.http.middlewares.oidc-auth.plugin.traefik-oidc-auth.provider.scopes=openid email profile"
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: unless-stopped
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true