services:
  otel-lgtm:
    hostname: "otel-lgtm"
    image: grafana/otel-lgtm:latest
    ports:
      - '4318:4318'
      - '4317:4317'
      - '3000:3000'
    stdin_open: true
    tty: true
    labels:
      # Service Labels
      - "traefik.enable=true"
      - "traefik.http.routers.pocketid.rule=Host(`${FQDN_TRAEFIK}`)"
      - "traefik.http.routers.pocketid.entrypoints=websecure"
      - "traefik.http.services.pocketid.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true