services:
  otel-lgtm:
    hostname: "otel-lgtm"
    container_name: "otel-lgtm"
    image: grafana/otel-lgtm:latest
    ports:
      - '4318:4318'
      - '4317:4317'
      - '3000:3000'
    stdin_open: true
    tty: true
    environment:
      - GF_SERVER_ROOT_URL=${FQDN_GRAFANA}
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN=true
      - GF_AUTH_GENERIC_OAUTH_NAME=PocketID
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES='openid profile email groups'
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=${OAUTH_AUTH_URL}
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
      - GF_AUTH_GENERIC_OAUTH_API_URL=${OAUTH_API_URL}
      - GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH=name
      - GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH=preferred_username
      - GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH=email
      - GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH=groups
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=roles
      - GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN=true

    labels:
      # Service Labels
      - "traefik.enable=true"
      - "traefik.http.routers.otel.rule=Host(`${FQDN_TRAEFIK}`)"
      - "traefik.http.routers.otel.entrypoints=websecure"
      - "traefik.http.services.otel.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy
    volumes:
      - /otel-lgtm-data:/var/lib/grafana
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true